### ISSUE TITLE
Update Readme.md and create changelog.md and contributing.md docs

### ISSUE THREAD

**Issue by EwoutH** [quaquel/EMAworkbench#158]
Update some of the documentation, specifically:
 - [ ] Update Readme with general information (#199)
 - [x] Create changelog.md based on previous release notes (#152 and #159)
 - [x] Create contributing.md on how to contribute and tag releases (#162)
