### ISSUE TITLE
Fix future/deprecation warning

### ISSUE THREAD

**Issue by EwoutH** [quaquel/EMAworkbench#201]
Fix all of the future/deprecations warnings currently present:

**Done ():** 
- [x] Fix `MarkerStyle(None)` deprecation in matplotlib by replacing it with `MarkerStyle('')`
- [x] Replace deprecated `.iteritems()` with `.items()` for dicts
- [x] Fix Matplotlib deprecation of `loc` as a positional keyword in `legend` functions 
- [x] Import `launcher` from `ipyparallel.cluster` instead of `ipyparallel.apps`

**To-do:**
- [ ] EMAworkbench/ema_workbench/analysis/parcoords.py:176: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
- [ ] EMAworkbench/ema_workbench/analysis/scenario_discovery_util.py:413: UserWarning: FixedFormatter should only be used together with FixedLocator
- [ ] Python/3.10.8/x64/lib/python3.10/site-packages/tornado/ioloop.py:265: DeprecationWarning: There is no current event loop
- [ ] Python/3.10.8/x64/lib/python3.10/site-packages/tornado/platform/asyncio.py:299: DeprecationWarning: There is no current event loop
- [ ] EMAworkbench/ema_workbench/em_framework/salib_samplers.py:137: DeprecationWarning: `salib.sample.saltelli` will be removed in SALib 1.5. Please use `salib.sample.sobol`

**Comment by EwoutH** [comment]
> 1. the future behavior is the desired behavior, so in principle, we don't need to do anything.

Great, moved to the _No action needed_-list.

> 3 and 4. No idea. Where is this warning being triggered in the workbench?

3 [here](https://github.com/quaquel/EMAworkbench/actions/runs/3322932831/jobs/5492637006#step:5:197) and 4 [here](https://github.com/quaquel/EMAworkbench/actions/runs/3322932831/jobs/5492637006#step:5:201) and 4 here. So all in `test/test_em_framework/test_ema_ipyparallel.py::TestLogWatcher::test_extract_level`.

**Comment by EwoutH** [comment]
> So another option is to require 1.4.6 and just move to sobol.

I think this is the most future-proof option.

**Comment by quaquel** [comment]
in place is the right behavior.

**Comment by EwoutH** [comment]
@quaquel A new FutureWarning popped up in the CI:

> EMAworkbench/EMAworkbench/ema_workbench/analysis/logistic_regression.py:256: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
self.peeling_trajectory = pd.concat(

It's happening here:

https://github.com/quaquel/EMAworkbench/blob/1071ac58021cd1664a7f125d1ccec02a8a16d7b4/ema_workbench/analysis/logistic_regression.py#L256

Can you check what's the intended behavior?

**Comment by quaquel** [comment]
The behavior change should not matter. In this code, a new set of rows is added to an existing data frame, so there should not be any NA columns anyway. The new behavior is thus fine.

**Comment by EwoutH** [comment]
Relevant ones fixed, moving others to 3.0

**Comment by EwoutH** [comment]
Few FutureWarnings with Pandas 2.2 (since [2.2.0rc0](https://github.com/pandas-dev/pandas/releases/tag/v2.2.0rc0)) in the [CI run](https://github.com/quaquel/EMAworkbench/actions/runs/7525058850/job/20480812051):

> /home/runner/work/EMAworkbench/EMAworkbench/ema_workbench/analysis/dimensional_stacking.py:407: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
>     pvt = pd.pivot_table(x_y_concat, values=ooi_label, index=rows, columns=columns, dropna=False)

> /home/runner/work/EMAworkbench/EMAworkbench/ema_workbench/analysis/logistic_regression.py:256: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
>     self.peeling_trajectory = pd.concat(

>   /home/runner/work/EMAworkbench/EMAworkbench/test/test_analysis/test_prim.py:387: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
>   You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
>   A typical example is when you are setting values in a column of a DataFrame, like:
>   
>   df["col"][row_indexer] = value
>   
>   Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.
>   
>   See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
>   
>     x.a[x.a > 5] = 5

> /home/runner/work/EMAworkbench/EMAworkbench/ema_workbench/analysis/scenario_discovery_util.py:928: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
>   You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
>   A typical example is when you are setting values in a column of a DataFrame, like:
>   
>   df["col"][row_indexer] = value
>   
>   Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.
>   
>   See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
>   
>     df_boxes.loc[unc][index[i]] = values.values

**Comment by EwoutH** [comment]
Back at 153 warnings again, see [this run](https://github.com/quaquel/EMAworkbench/actions/runs/10780367544/job/29895977379) for example.
